<?
/*

XMB 1.6 v2b Magic Lantern Final
© 2001 - 2002 Aventure Media & The XMB Developement Team
http://www.aventure-media.co.uk
http://www.xmbforum.com

For license information, please read the license file which came with this edition of XMB

*/
require "./header.php";
require "./xmb.php";
if(!$xmbuser || !$xmbpw) {
	$xmbuser = "";
	$xmbpw = "";
	$status = "";
}

if($status != "Administrator") {
	echo "$lang_notadmin";
	exit;
}

$cploc = $HTTP_SERVER_VARS["REQUEST_URI"]; 
if(getenv(HTTP_CLIENT_IP)) { 
$ip = getenv(HTTP_CLIENT_IP); 
} elseif(getenv(HTTP_X_FORWARDED_FOR)) { 
$ip = getenv(HTTP_X_FORWARDED_FOR); 
} else { 
$ip = getenv(REMOTE_ADDR); 
} 
$time = time(); 
$string = "$xmbuser|#||#|$ip|#||#|$time|#||#|$cploc\n";
$filehandle=fopen("./cplogfile.log","a"); 
flock($filehandle, 2); 
fwrite($filehandle, $string); 
fclose($filehandle); 
?>

<?
if($view == "index") { 
?> 
<tr bgcolor="<?=$altbg2?>"> 
<td align="center"> 
<br />

<?
 $file="index_log.log";
 $fp=@fopen($file,"r");
 $rawread=fread($fp, filesize($file));
 fclose($fp);
 $output= explode("|", $rawread);
 $nb_entries=count($output);
 $nb_entries1 = $nb_entries
?>
<html>
<title>XMB Index Activity Logs</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<style type="text/css">
<!--
A:link { COLOR: white; TEXT-DECORATION: none }
A:visited { COLOR: #cccccc; TEXT-DECORATION: none }
A:active { COLOR: #cccccc; TEXT-DECORATION: none }.text {  font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 7pt; font-weight: normal; color: #000000; text-decoration: none}
-->
</style>

<body bgcolor="#1F3145" text="#FFFFFF" link="#FFFFFF" vlink="#FFFFF" alink="#CCCCCC">
<p align="center"><font color="#FFFFFF" size="1"><b><font face="Verdana, Arial"><b>Index Logs<br></b>Generated By XMB 1.6 Magic Lantern Logs Module<b><br>This information cannot be used for distribution of user details or to cause damage to the host/IP of a user.<br></font></b></font></p>
<form name="form1" method="post" action="">
  <i><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#000000">
  <div align="center"></div>
  </font></i>
  <div align="center">
    <div align="center"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#FFFFFF">Show
      the last
      <select name="disp_nb">
        <option value="10"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#FFFFFF"><i>10</i></font></option>
        <option value="25"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#FFFFFF"><i>25</i></font></option>
        <option value="50"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#FFFFFF"><i>50</i></font></option>
        <option value="75"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#FFFFFF"><i>75</i></font></option>
        <option value="100"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#FFFFFF"><i>100</i></font></option>
        <option value="150"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#FFFFFF"><i>150</i></font></option>
       <option value="200"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#FFFFFF"><i>200</i></font></option>
        <option value="all"><font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#FFFFFF"><i>All</i></font></option>
      </select>
      users.
      <input type="submit" name="go" value="Show" action="view.php">
      </font></i></div>
  </div>
  <font face="Verdana, Arial, Helvetica, sans-serif" size="2" color="#FFFFFF"><i>
  </i></font>
</form>
<hr width="70%" size="1" noshade>
<table width="0%" border="1" align="center" bordercolorlight="#7E868E" bordercolordark="#003063" bgcolor="#7E868E" bordercolor="#7E868E" class="text">
<?
 if (!isset($disp_nb)){ $disp_nb = 75; }
 if ($disp_nb=="all") { $disp_nb = $nb_entries; }
 $nb_entries1 = $nb_entries - $disp_nb;
 ?><font face="Verdana" size="1">Here are the details of the last<b> <? echo $disp_nb; ?> </b> visitors to index.php
 <?
 for ($count1 = $nb_entries; $count1 >= $nb_entries1; $count1--) {
 echo $output[$count1];
};
?>
</table>
<p align="center"><b><?php echo  $nb_entries; ?></b> Visitors Since Reset</p>
<br><font face="Verdana, Arial, Helvetica, sans-serif" size="-2" color="#FFFFFF">
<center>This script is © Aventure Media 2002 - this script is not to be modified in any form<br>
<a href="http://www.aventure-media.co.uk">www.aventure-media.co.uk</a><br><br>
<? 
} 

?>