<select name="timeoffset1">
<option value="-12"   <?= $sel['1'] ?>><?= $lang['timezone1'] ?></option>
<option value="-11"   <?= $sel['2'] ?>><?= $lang['timezone2'] ?></option>
<option value="-10"   <?= $sel['3'] ?>><?= $lang['timezone3'] ?></option>
<option value="-9.5"  <?= $sel['37'] ?>><?= $lang['timezone37'] ?></option>
<option value="-9"    <?= $sel['4'] ?>><?= $lang['timezone4'] ?></option>
<option value="-8"    <?= $sel['5'] ?>><?= $lang['timezone5'] ?></option>
<option value="-7"    <?= $sel['6'] ?>><?= $lang['timezone6'] ?></option>
<option value="-6"    <?= $sel['7'] ?>><?= $lang['timezone7'] ?></option>
<option value="-5"    <?= $sel['8'] ?>><?= $lang['timezone8'] ?></option>
<option value="-4"    <?= $sel['9'] ?>><?= $lang['timezone9'] ?></option>
<option value="-3.5"  <?= $sel['10'] ?>><?= $lang['timezone10'] ?></option>
<option value="-3"    <?= $sel['11'] ?>><?= $lang['timezone11'] ?></option>
<option value="-2"    <?= $sel['12'] ?>><?= $lang['timezone12'] ?></option>
<option value="-1"    <?= $sel['13'] ?>><?= $lang['timezone13'] ?></option>
<option value="0"     <?= $sel['14'] ?>><?= $lang['timezone14'] ?></option>
<option value="1"     <?= $sel['15'] ?>><?= $lang['timezone15'] ?></option>
<option value="2"     <?= $sel['16'] ?>><?= $lang['timezone16'] ?></option>
<option value="3"     <?= $sel['17'] ?>><?= $lang['timezone17'] ?></option>
<option value="3.5"   <?= $sel['18'] ?>><?= $lang['timezone18'] ?></option>
<option value="4"     <?= $sel['19'] ?>><?= $lang['timezone19'] ?></option>
<option value="4.5"   <?= $sel['20'] ?>><?= $lang['timezone20'] ?></option>
<option value="5"     <?= $sel['21'] ?>><?= $lang['timezone21'] ?></option>
<option value="5.5"   <?= $sel['22'] ?>><?= $lang['timezone22'] ?></option>
<option value="5.75"  <?= $sel['23'] ?>><?= $lang['timezone23'] ?></option>
<option value="6"     <?= $sel['24'] ?>><?= $lang['timezone24'] ?></option>
<option value="6.5"   <?= $sel['25'] ?>><?= $lang['timezone25'] ?></option>
<option value="7"     <?= $sel['26'] ?>><?= $lang['timezone26'] ?></option>
<option value="8"     <?= $sel['27'] ?>><?= $lang['timezone27'] ?></option>
<option value="9"     <?= $sel['28'] ?>><?= $lang['timezone28'] ?></option>
<option value="9.5"   <?= $sel['29'] ?>><?= $lang['timezone29'] ?></option>
<option value="10"    <?= $sel['30'] ?>><?= $lang['timezone30'] ?></option>
<option value="10.5"  <?= $sel['36'] ?>><?= $lang['timezone36'] ?></option>
<option value="11"    <?= $sel['31'] ?>><?= $lang['timezone31'] ?></option>
<option value="12"    <?= $sel['32'] ?>><?= $lang['timezone32'] ?></option>
<option value="12.75" <?= $sel['35'] ?>><?= $lang['timezone35'] ?></option>
<option value="13"    <?= $sel['33'] ?>><?= $lang['timezone33'] ?></option>
<option value="14"    <?= $sel['34'] ?>><?= $lang['timezone34'] ?></option>
</select>
